<!DOCTYPE html>
<html>

<!-- Life-cycle Management Applet Collection
     Paul Laibach - LcMS Concept and Implementation
     Connor Hayes - Applet Development and Testing
-->

<head>

   <title>LcMS Device Lookup v1.3</title>
   <link rel="stylesheet" type="text/css" href="lookup_applets.css">

</head>

<body>

   <h3>
      Life-cycle Management System<br>
      -- Device Lookup v1.3 --
   </h3>

   <form name="lookupForm" action="machinetype.php" method ="POST">
      <input type="text" autofocus placeholder="gimme something" onFocus="this.select()" name="model" value="<?php if (isset($_POST['model'])) echo $_POST['model']; ?>"><br><br>
      <input type="submit" class="submit">
   </form>

   <h4>
      Furry search of LcMS devices
   </h4>

   <div class="wrapper">
      <p>Lorem ipsum dolor sit amet, sed porta elit sed ac, suspendisse a ultrices nulla odio at adipiscing, sed lectus lectus wisi aenean nec, orci felis dolor sit nullam augue, nulla cras semper. Consectetuer vitae conubia pellentesque massa eu, eget arcu porta, officia ipsum magna nisl. Cum consequat. At aliquam praesent ipsum, quis dolor dui justo eget magna, semper pellentesque leo mollis ut, at cursus curabitur, porttitor nulla ipsum mauris at neque. Accumsan in urna nulla ac tellus senectus, mattis pellentesque. Dictum donec sodales metus.</p>
      <p>Mi placerat congue, libero aliquam, metus egestas at neque, nulla vel ornare, risus faucibus lacinia augue neque incididunt massa. Dolor scelerisque tortor tempus, hendrerit curabitur, non praesent ligula ad pede elementum, orci suscipit mi massa ullamcorper, justo amet amet. Ultricies vel ipsum eleifend, pulvinar lectus mattis volutpat sed et ad, ut erat lectus adipiscing, lobortis tellus id ante volutpat, tellus nullam turpis netus. Purus rutrum bibendum est ultrices pellentesque dignissim, mi duis commodo volutpat porttitor vitae lectus. Sem neque id, consectetuer placerat odio aliquet malesuada arcu, arcu wisi. Integer velit turpis vivamus tempus, lectus eget ligula interdum adipiscing ligula ligula, at ipsum urna et nec mauris tristique, urna cras felis sollicitudin at neque, wisi ipsum cras. Mollis gravida mi vestibulum amet donec enim, praesent eros donec bibendum, risus quam sem platea ridiculus, amet feugiat et, aenean quod fermentum.</p>
      <p>Vehicula aenean tristique sit sapien, ut ullamcorper, ante volutpat. Risus consequat, condimentum elit duis. Faucibus turpis placerat erat commodo. Tellus elit hac in ut curabitur, velit at erat egestas. Mauris elit in euismod vitae. Arcu posuere pellentesque pede, viverra urna arcu fringilla ante ultricies. Massa ut ante aliquam ipsum nisl cras, sociis quam est nulla nunc ultrices. Lorem orci leo nunc. Mi faucibus lacus, sed ornare sapien, lectus dolor gravida molestie feugiat, at et id suspendisse praesent blandit. Nunc ipsum scelerisque elit turpis risus, suspendisse est est vestibulum ipsum, vivamus vestibulum. Suspendisse montes etiam ipsum est ut, metus ligula, vel elit etiam in eget, metus pede bibendum tellus, accumsan dapibus libero ut. Dolor lacus in.</p>
      <p>Ante nunc torquent vel morbi facilisis, lobortis pretium donec cras morbi vivamus vehicula, imperdiet augue tincidunt nibh, metus purus volutpat, sed gravida consequatur justo aptent leo. Tincidunt cras, lacus ac nibh hac magna consectetuer, nec vel ultrices, lectus placerat lobortis ipsum pulvinar vestibulum arcu. Metus placerat, malesuada pellentesque duis aenean. Vestibulum vestibulum malesuada habitasse luctus, aenean dolor aliquam dapibus nec. Ornare magna pulvinar, urna est lacus euismod ultricies, ante suspendisse in eget, euismod temporibus et vel, et lorem vestibulum. Sed velit, maecenas tellus sagittis, cursus mus cras morbi praesent ullamcorper posuere. Et eget eget proin orci, tempor gravida eros nulla bibendum, eleifend ac integer placerat, quis amet at, lobortis varius ligula non cras. Neque ut, nulla elit mauris erat tempus pellentesque, molestie donec donec odio ut mi libero. Sapien mauris, elit eleifend sed nibh lorem morbi, neque ipsum ullamcorper pretium, vel id dictum id accumsan.</p>
      <p>Interdum eget vestibulum imperdiet, lacus in dui, adipiscing tempor, sit feugiat nec leo volutpat. Lobortis elit ut rhoncus. Cursus quam luctus nunc lorem ut magna, pede dolor, bibendum elit convallis amet dui, nonummy adipiscing laoreet bibendum posuere posuere. Sed nulla donec justo elit, vestibulum pede libero, lacinia torquent eget donec pellentesque, aliquam purus consequat libero, orci nulla risus sollicitudin suspendisse non. Morbi velit interdum sed etiam ante gravida, ligula sem consectetuer pede facilisis pellentesque, at cras urna suspendisse nascetur quam. Pede quis aliquam purus neque id pede, sit wisi porta. Eu vestibulum magna egestas porta, lacus ante primis ipsum ac. Curabitur lacinia pede, eros integer pharetra dapibus, ut neque, porttitor pulvinar eget lorem ultricies sed, aliquam enim vestibulum suspendisse gravida quam sem. Urna purus nostra accumsan faucibus, fringilla praesent, et id gravida suscipit imperdiet. Est aliquet ullamcorper, sit metus eget ultrices, pretium fermentum vivamus faucibus metus in mauris, sem vulputate. Viverra rhoncus, fusce donec commodo orci per wisi, ullamcorper nisl vestibulum.</p>
      <p>Pellentesque malesuada sollicitudin sit erat nulla quis. Per lectus habitasse vitae, sed justo in etiam in ut magna. Sit amet sed non duis pulvinar lorem, diam praesent at morbi sit urna, sed non nam in sed parturient, viverra lorem lobortis suscipit. Mattis leo quam ligula amet per eu, bibendum porttitor est non tortor, vestibulum vivamus libero molestie platea sed, quis id, rutrum fermentum rutrum placerat id. Vestibulum provident est nonummy a vivamus quisque, ut rutrum pulvinar orci, parturient nunc blandit nec cum amet, vestibulum donec elit sed accumsan, integer nam ligula. Arcu egestas. Nullam lobortis amet sit consequat. Cursus cursus. Libero massa venenatis morbi nulla convallis.</p>
      <p>Justo dui, venenatis nonummy dignissim, atque sem, id adipiscing, vestibulum tempor. Porttitor non eget etiam, auctor enim, diam arcu sapien. Minima ac maecenas praesent, auctor felis, elit scelerisque ultricies aenean venenatis pellentesque. Vestibulum nostra in, ornare enim tincidunt minim. Ut tortor nec mauris, aliquam libero morbi quam non odio. Sodales venenatis vitae est, rhoncus aut dui pulvinar sem lacinia iaculis, mollis nec, luctus ultricies molestie vitae. Pede tortor et iaculis tortor risus, suspendisse lacus eleifend neque tempor ut inceptos, vehicula curabitur at sed neque, praesent eu in suspendisse suspendisse euismod. Arcu eu, inceptos vitae.</p>
      <p>Dignissim ac, nullam dignissimos eros ipsum, etiam donec praesent, sed proin. Morbi dolor at elit. Porta vitae, ante sollicitudin pellentesque, rhoncus arcu facilisis hac eget massa, suscipit porta, gravida neque sit integer integer. Cursus ac et wisi, semper metus autem ligula, mauris pharetra, vestibulum lorem leo, nullam maecenas. Et tellus egestas massa ornare, curabitur fames lorem turpis id mauris sit, erat elementum molestie, pede nulla laoreet massa, et eleifend eu semper blandit nibh. Sed vestibulum fames mi risus, ipsum gravida duis sit magna, in ultricies, in vel aenean tincidunt viverra egestas vestibulum. Dapibus blandit tempus dui, venenatis amet vel voluptatibus faucibus fringilla etiam, rutrum quam vel tortor, mi tincidunt. Placerat laoreet iaculis egestas et.</p>
      <p>Eligendi est litora. Feugiat adipiscing, mattis enim aenean venenatis. Vel ultricies do sed, hac cursus, luctus ante elit nibh ipsum. Fusce eros vitae maecenas et dolores, leo molestie, wisi diam, voluptas adipiscing sit pede non neque vitae, nibh ac nulla vitae vivamus magna ut. Morbi hac nulla ut porta ipsum, quam sodales quam quam quam. Lacus in ut mi gravida neque. Morbi ullamcorper quam turpis mauris. In mauris eget, aliquam integer fringilla justo massa augue, ut et dapibus dolor sollicitudin neque maecenas, sit erat vestibulum porttitor, proin magna sed mauris morbi tempus mauris. Vel duis. Aenean vitae, pulvinar sit imperdiet ridiculus.</p>
      <p>Sed cursus, eu erat lorem. In mollis, mauris nulla eu eget nibh sociis, risus ligula mus donec. Per at conubia magnis maecenas, non eget donec, placerat diam inceptos lectus, maecenas vitae. Lorem eu porta, et ante pede curabitur pharetra habitasse aliquam, nisl nunc. Eleifend nullam vitae dictumst vitae metus, morbi nulla dapibus.</p>
      <p>Ut est varius arcu nec quam massa, urna ultricies, mauris varius diam lectus, morbi quis nibh felis, tincidunt et senectus mi in ut ultricies. Nonummy ut inceptos orci eleifend ac, turpis duis tincidunt, maecenas id wisi, amet morbi aliquet habitasse pede, consequat fringilla lacus mattis mollis platea et. Aliquip aliquet quis, eget felis est dictum nulla, ipsum in consequat. Wisi ac nunc class massa massa mauris, sem non ac. Conubia in orci non, mattis ridiculus amet, quam purus dui tellus quis odio, gravida nunc, amet laoreet auctor in vel risus ultricies. Amet lorem nec amet, aliquam amet vivamus, blandit est, ac justo sollicitudin. Nec est mauris nec. Aliquam purus, sed adipiscing vivamus eget nec ac, vitae risus. Lorem nulla arcu eu in, nec egestas porttitor, in mauris ut ut duis. Sunt eget rhoncus et cras lorem.</p>
      <p>Eros ipsum, ut ultricies nibh ac. Dui vel nunc rhoncus sed luctus morbi, consequat est wisi, laoreet eget per, maecenas class tellus varius quis, maecenas a a porta imperdiet venenatis. Purus viverra, massa sociosqu ipsum orci bibendum et, sodales sed commodo, eu quam id metus commodo pellentesque. Sit quam. Risus phasellus. Est neque ipsum euismod id eu phasellus, ut pellentesque nam tempus velit leo, enim lectus dui nibh vel et, vel pellentesque cumque, in ante libero. At vitae metus, gravida et, erat quis scelerisque elit fringilla mollis, amet ac aenean.</p>
   </div>
</body>

</html>
